### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by felipemarcos** [FelipeMarcos/cabelo#1]
In no particular order:

- [ ] Nice documentation
- [ ] Performance tests
- [ ] Mobile tests
- [ ] More tests
- [ ] Examples
- [ ] Add more comments
- [ ] Improve instance.destroy() method
- [ ] Easing for each property
- [ ] Add callbacks to tweens
- [ ] Do the dishes
- [ ] Trigger update callback on page load if scrollStop is > 0
- [ ] Add relative values. E.g.: +=100
- [ ] Add xPercent and yPercent so _x_ and _y_ can be animated with translate(-50%, -50%)
- [ ] Allow scrollTo to be cancellable
- [ ] Allow svg dashoffset to be animated
- [ ] Does CSS variables works?
- [ ] Snap to duration
- [ ] Sticky Section
- [ ] Round z-index value
- [x] Color animations
- [x] Edge cases
- [x] Animate transform in the same element separately
- [x] Multiple units (px, %, rem, em, vh, and etc)
- [x] Allow to animate the same element separately
- [x] Allow relative durations like skrollr: top-bottom, middle-middle, middle-top
- [x] Add animated scrollTo method
- [x] Stagger
- [x] Add bezier package (https://github.com/gre/bezier-easing)
- [x] Add more easings
